FROM public.ecr.aws/aws-observability/aws-otel-collector:latest

COPY ./collector-config.yaml /opt/aws/aws-otel-collector/etc/collector-config.yaml

CMD [ "/otelcontribcol", "--config", "/opt/aws/aws-otel-collector/etc/collector-config.yaml"]
